# Generated by Django 4.0 on 2022-08-01 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_project_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='last_updated',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='latest_update',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
    ]
