# Generated by Django 4.0 on 2022-08-02 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_project_last_updated_project_latest_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='last_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stage',
            name='date_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
