# Generated by Django 4.0 on 2022-08-03 04:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_alter_project_last_updated_alter_stage_date_updated'),
    ]

    operations = [
        migrations.CreateModel(
            name='Repo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
            ],
        ),
        migrations.AlterField(
            model_name='project',
            name='repo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.repo'),
        ),
    ]
