# Generated by Django 4.0 on 2022-05-21 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='address_two',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
