# Generated by Django 4.0 on 2022-06-05 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('icon_color', models.CharField(blank=True, max_length=254, null=True)),
                ('icon_class', models.CharField(blank=True, max_length=254, null=True)),
                ('description', models.TextField(max_length=1200)),
            ],
        ),
    ]
