# Generated by Django 4.0 on 2022-06-21 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_skills'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('client', models.ImageField(upload_to='')),
            ],
        ),
    ]
