# Generated by Django 4.0 on 2022-07-14 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0004_client'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('title', models.CharField(max_length=254)),
                ('heading', models.CharField(max_length=254)),
                ('paragraph', models.TextField(max_length=2000)),
                ('bullet_one', models.CharField(max_length=254)),
                ('bullet_two', models.CharField(max_length=254)),
                ('bullet_three', models.CharField(max_length=254)),
            ],
        ),
    ]
