# Generated by Django 4.0 on 2022-07-17 19:40

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0006_testimonial'),
        ('portfolio', '0002_project_image_three_project_image_two'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='about.client'),
        ),
        migrations.AddField(
            model_name='project',
            name='date_completed',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='project_description',
            field=models.CharField(default='Project Description', max_length=2000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='project_title',
            field=models.CharField(default='Project Title', max_length=254),
            preserve_default=False,
        ),
    ]
